spring:
  datasource:
    url: jdbc:mysql://localhost:3306/circle?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true&amp;useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: haili888
    filters: stat,wall  # 监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
    initial-size: 100      # 初始化时建立物理连接的个数
    max-active: 100        # 最大连接池数量
    min-idle: 50          # 最小连接池数量
    max-wait: 6000        #获取连接时最大等待时间，单位毫秒
    pool-prepared-statements: true   #  是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大
    max-open-prepared-statements: 20    # 要启用PSCache，必须配置大于0
    validation-query: select 'x'  #  用来检测连接是否有效的sql
    test-on-borrow:  false  # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    test-on-return: false  # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    test-while-idle: true             # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    time-between-eviction-runs-millis: 6000    #  1) Destroy线程会检测连接的间隔时间    2) testWhileIdle的判断依据
    min-evictable-idle-time-millis: 30000
    maxPoolPreparedStatementPerConnectionSize: 20  # Destory线程中如果检测到当前连接的最后活跃时间和当前时间的差值大于minEvictableIdleTimeMillis，则关闭当前连接。
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  thymeleaf:
    enabled: true
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false  #关闭缓存
    prefix: classpath:/templates/  #模板前缀
    suffix: .html
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,classpath:/templates/, file:${web.file-abpath}

server:
  port: 9999
#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.shurencircle.entity  #扫描的实体路径
  mapper-locations: classpath:mybatis/mapper/*.xml

#定义上传文件的绝对路径和访问的相对路径
web:
  file-abpath:
    E:/test/shurencircle
  img-relapath:
    /img/
  video-relapath:
    /video/



#打印sql
logging:
  level:
    com:
      shurencircle:
        mapper: DEBUG

